version: '3.9'
services:
  backend:
    build:
      context: ./todoapp-backend
    container_name: todo-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/tmp/ToDoApp.db
    networks:
      - todo-network

  frontend:
    build:
      context: ./todoapp-ui
    container_name: todo-ui
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge